baseURL = "https://selek.netlify.app/"
theme = "hugo-ficurinia"
title = "Apo's tech blog"

author = "Abdullah Selek"
copyright = "Abdullah Selek - [MIT License](https://github.com/abdullahselek/selek.tech/blob/main/LICENSE)."

paginate = 5
summaryLength = 30

[params]
    description = "Tech blog about AI, ML and Data Science"
    author = "Abdullah Selek"
    logo = "/logo.svg"
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png"
    svgicon = "/logo.svg"
    icon512 = "/android-chrome-512x512.png"
    
    imageInArticlePreview = true

    enableShareOnFediverse = true

    enableRelatedArticles = true
    relatedArticlesNum = 2 
    forceRedirect = true

    # enable analytics using Umami
    umamiScriptUrl = "https://eu.umami.is/script.js"
    umamiWebsiteId = "f42ea43e-742b-4364-b4fa-332091608b1f"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = false
        tabWidth = 4
        style = "dracula"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[menu]
    [[menu.icons]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/abdullahselek"
        weight = 10
